# Generated by Django 5.1.7 on 2025-04-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_staff_department_remove_staff_team_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Engineer', 'Engineer'), ('Team Leader', 'Team Leader'), ('Department Leader', 'Department Leader'), ('Senior Manager', 'Senior Manager'), ('Admin', 'Admin')], default='Engineer', max_length=20),
        ),
    ]
