# Generated by Django 5.1.7 on 2025-04-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='progress',
            field=models.CharField(choices=[('Improving', 'Improving'), ('Stable', 'Stable'), ('Declining', 'Declining')], max_length=15),
        ),
    ]
