# Generated by Django 5.1.7 on 2025-04-30 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_vote_progress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
